# Generated by Django 2.2.5 on 2020-06-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='tb_addresses',
        ),
    ]
