# Generated by Django 2.2.5 on 2020-06-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200625_0845'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='tb_address',
        ),
    ]
