# Generated by Django 2.2.5 on 2020-06-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20200624_0345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='tb_areas',
        ),
    ]
